server {
    listen 80;
    server_name www.yyy301.com;

    # 将本项目 public 目录中的全部内容上传到此目录
    root /var/www/canlexiang;
    index index.html;

    location = / {
        return 302 /login/;
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
